version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: osukhankin/foodgram_final:latest
    restart: always
    volumes:
      - media_value:/app/media/
      - static_admin_value:/app/static/admin/
      - static_rest_framework_value:/app/static/rest_framework/
      - static_data_value:/app/static/data/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: osukhankin/foodgram_frontend:latest
    volumes:
      - ./frontend/frontend/:/app/result_build/
    depends_on:
      - backend


  nginx:
    image: nginx:1.19.3
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - media_value:/usr/share/nginx/html/media/
      - static_admin_value:/usr/share/nginx/html/static/admin/
      - static_rest_framework_value:/usr/share/nginx/html/static/rest_framework/
      - static_data_value:/usr/share/nginx/html/static/data/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./frontend/frontend/build/:/usr/share/nginx/html/
      - ./docs/docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot



volumes:
  static_admin_value:
  static_rest_framework_value:
  static_data_value:
  media_value:
  postgres_data:
