version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build: ../backend/foodgram/
    restart: always
    volumes:
      - media_value:/app/media/
      - static_admin_value:/app/static/admin/
      - static_rest_framework_value:/app/static/rest_framework/
      - static_data_value:/app/static/data/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - media_value:/usr/share/nginx/html/media/
      - static_admin_value:/usr/share/nginx/html/static/admin/
      - static_rest_framework_value:/usr/share/nginx/html/static/rest_framework/
      - static_data_value:/usr/share/nginx/html/static/data/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build/:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend

volumes:
  static_admin_value:
  static_rest_framework_value:
  static_data_value:
  media_value:
  postgres_data:
