# Generated by Django 3.2 on 2023-04-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredient_options'),
        ('recipes', '0003_recipeingredient_unique_recipe_ingredient'),
    ]

    operations = [
    ]
